apiVersion: v1
kind: Service
metadata:
  labels:
    app: chitchat-classifier
  name: chitchat-classifier
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: chitchat-classifier
  type: LoadBalancer
