apiVersion: v1
kind: Service
metadata:
  labels:
    app: pre-analyzer
  name: pre-analyzer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: pre-analyzer
  type: LoadBalancer
