apiVersion: v1
kind: Service
metadata:
  labels:
    app: rule-entity-extractor
  name: rule-entity-extractor
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: rule-entity-extractor
  type: LoadBalancer
